version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vibewater_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: vibewater_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - vibewater_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibewater_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=vibewater_db
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - vibewater_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vibewater_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - vibewater_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongodb_data:

networks:
  vibewater_network:
    driver: bridge
